### ISSUE TITLE
Configuring with default workflows, role management, and admin user

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/night_moves#1]
Here's everything I did after starting the app up, to get it operational:

```bash
## local
$ docker start night_moves
$ docker exec -it -u root night_moves bash

## on image - as root
$ bundle exec rake hyrax:default_collection_types:create
Default collection type is user_collection
Default collection type is admin_set
## https://github.com/samvera/hyrax/wiki/Making-Admin-Users-in-Hyrax#install-hydra-role-management
$ echo "gem 'hydra-role-management'" >> Gemfile
$ bundle install
[...]
Bundle complete! [...]
$ rails generate roles
Running via Spring preloader in process 517
      create  db/migrate/20200421170424_user_roles.rb
      insert  app/models/user.rb
$ rails db:migrate
== 20200421170424 UserRoles: migrating ========================================
[...]
== 20200421170424 UserRoles: migrated (0.0316s) ===============================
```

After this point I tried to use the web UI to make a user to finish this step: https://github.com/samvera/hyrax/wiki/Making-Admin-Users-in-Hyrax#add-an-initial-admin-user-via-command-line

...and I started getting route errors on "/"

When I restart the container I get nothing from the web UI: 

```
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by crowesn** [comment]
I think the problem is trying to run the hydra:server task - it doesn't seem stable. I'll break those services out and work on adding the config. I was able to get through the role creation and assignment but it's not permitting me to see the /roles page.. I'll fuss with it.
